# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool: 'unity'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'standalone'
    unityProjectPath: 'E:\\UnityProjects\\MyProjects\\CockRoach'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'drop'
